stages: 
  - build
  - deploy

install-dependencies:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: dev
  variables:
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  needs:
    - install-dependencies
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
    - npm install -g serverless
    - sls deploy --stage=dev
